set ruler
set nu
set tabstop=4
set nocompatible
set backspace=indent,eol,start
set nowrap
set shiftwidth=4
set expandtab
set nobackup
set nowritebackup
set noswapfile
set noundofile
set clipboard=unnamed
syntax on
